# Site settings
title: DUSTI.X(yz)
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Bezahlbare open source DIY Feinstaub-Sensoren
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dusti.xyz" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: opendata-stuttgart

# Build settings
markdown: kramdown
